# docker-compose.yml


services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: furniture-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    environment:
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=moebelDB

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: furniture-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/moebelDB
      - PORT=3001

  # Frontend Service
  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    container_name: furniture-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001

volumes:
  mongodb_data: